### ISSUE TITLE
Creation of BLAST database error

### ISSUE THREAD

**Issue by Iris95H** [genenotebook/genenotebook#109]
For one of my genomes, creating a blast database gives the following error:

## LOG: 2020-06-03T10:20:03.890Z scanning 28021 genes
PROGRESS: BLDCa5jmZLeafrPbk JSMjNsw9kDzM8Wajx: 0 out of 28021 (0%)
## WARNING: 2020-06-03T10:20:04.031Z TypeError: Cannot read property 'phase' of undefined
at transcripts.map.transcript (imports/api/util/util.js:169:79)
at Array.map (<anonymous>)
at getGeneSequences (imports/api/util/util.js:159:33)
at Genes.find.forEach (imports/api/jobqueue/process-makeBlastDb.js:35:5)
at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1107:16)
at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:887:44)
at Promise.asyncApply (imports/api/jobqueue/process-makeBlastDb.js:29:28)
at /lustre/BIF/nobackup/xvand109/Tools/miniconda3/share/genenotebook-0.1.16-3/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

Would it be possible to see which genes cause this issue?
Thanks in advance!

**Comment by holmrenser** [comment]
This should be fixed in v0.3.0
